Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -6,43 +6,43 @@ on:
   pull_request:
     branches: [ main ]
 
-# env:
-#   DB_USER: root
-#   DB_PASSWORD:
-  
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "pr check"
-  pr-check:
-    # The type of runner that the job will run on
+  build-and-health-check:
     runs-on: ubuntu-latest
-    # Steps represent a sequence of tasks that will be executed as part of the job
     env:
-      DB_DATABASE: database4
+      DB_DATABASE: demo
       DB_USER: root
-      DB_PASSWORD: password
+      DB_PASSWORD: Qq18284530122
+
     steps:
-      - name: Start mysql service
+      - uses: actions/checkout@v3
+      - name: Start MySQL Service
         run: |
           sudo systemctl start mysql
-          mysql -uroot -proot --connect-expired-password -e "Alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'"
+          mysql -uroot -proot --connect-expired-password -e "Alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Qq18284530122'"
           mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' 
-      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
-      - uses: actions/checkout@v1
-      #Set up JDK 11
-      - name: Set up JDK
-        uses: actions/setup-java@v1
+
+      - name: Set up JDK 19
+        uses: actions/setup-java@v3
         with:
-          java-version: '19'
-      #Set up Maven cache
-      - name: Cache Maven packages
-        #This action allows caching dependencies and build outputs to improve workflow execution time.
-        uses: actions/cache@v1
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: check healthz API
-        with: |
-          curl -vvvv http://localhost:8080/healthz 
+          java-version: 19
+          distribution: 'temurin'
+          cache: maven
+      - name: Build with Maven
+        run: |
+          mvn -B package --file pom.xml
+      # using maven to run spring boot application
+      - name: Run health check
+        env:
+          DATABASE_NAME: csye6225
+          DATABASE_USERNAME: root
+          DATABASE_PASSWORD: Qq18284530122
+          DATABASE_ENDPOINT: 127.0.0.1
+        run: |
+          timeout --signal=SIGINT 5m mvn spring-boot:run &
+          sleep 30  # Give the application some time to start
+          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8080/healthz)
+          if [[ "$response" -ne 200 ]] ; then
+            echo "Health check failed with HTTP status code $response"
+            exit 1
+          fi
